### ISSUE TITLE
Not broadcasting on all interfaces

### ISSUE THREAD

**Issue by andosmith** [mafintosh/multicast-dns#32]
I think something in the documentation may be incorrect.  In creating a new mdns instance this is one of the option choices: 

> interface: '192.168.0.2' // explicitly specify a network interface. defaults to all

We were finding that we were only seeing it available on one interface.  Looking at index.js: 

> socket.addMembership(ip, opts.interface)

According to [documentation on dgram](https://nodejs.org/api/dgram.html) (the socket), addMembership defaults to a single interface (chosen by the operating system), and if multiple interfaces are desired addMembership should be called multiple times, once per interface.  What do you think about taking an array of addresses and calling addMembership on each?

**Comment by dlancho** [comment]
Hi,

As far as I know, in addMembership the passed interface is only to restrict what interface you should listen to, but not which to send.

The problem I found is that when sending packets, the system selects one interface based on unknown (to me) rules (it does not select based on routing table, and it changes every couple of minutes).

In order to broadcast in one specific interface, I had to modify the socket binding by including the same _opts.interface_ as it is in the addMembership call. 

```
var bind = thunky(function (cb) {
    if (!port) return cb(null)
    socket.once('error', cb)
    socket.bind(port, opts.interface, function () {
      socket.removeListener('error', cb)
      cb(null)
    })
  })
```

The restriction then is that I cannot pass an encoded interface idx as an IP, and I have to pass the interface IP.

I am not sure if there is another way of controlling what interface to broadcast to, but it would be nice to know :-)

**Comment by mafintosh** [comment]
I think this is fixed in latest... If not please reopen.
